#! /bin/bash

cfgname="/tmp/scad$$.cfg"

cat << EOF > $cfgname
#! /usr/bin/wget --config

#===========================================================================
verbose = on

add_hostdir = off
cut_dirs = 1
timestamping = on
adjust_extension = on
convert_links = on
backup_converted = off

recursive = on
reclevel = 4
no_parent = on
page_requisites = on
robots = off

span_hosts = on
domains = en.wikibooks.org, upload.wikimedia.org
tries = 10
# wait = 0.7
dir_prefix = debian/source/appdoc
logfile = log
#===========================================================================
EOF

wget --config $cfgname http://en.wikibooks.org/wiki/OpenSCAD_User_Manual \
    --accept-regex '(/OpenSCAD_User_Manual(/.*)?(\.htm(l)?)?$)|(\.png$)|(\.ico$)|(\.jpg$)|(\.jpeg$)' \
#    --reject-regex '/(File)|(Special):.*'

mv OpenSCAD_User_Manual.html index.html 
rm $cfgname

exit 0
