Document: openscad
Title: Debian openscad Manual
Author: <insert document author here>
Abstract: This manual describes what openscad is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openscad/openscad.sgml.gz

Format: postscript
Files: /usr/share/doc/openscad/openscad.ps.gz

Format: text
Files: /usr/share/doc/openscad/openscad.text.gz

Format: HTML
Index: /usr/share/doc/openscad/html/index.html
Files: /usr/share/doc/openscad/html/*.html
